version: "3.7"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"


services:
  database:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/postgres:12.4-alpine"
    environment:
      - POSTGRES_DB=credit_robot_ru
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
    logging: *default-logging
    restart: "${DOCKER_RESTART:-no}"
    env_file:
      - ../.env

  server:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:dev"
    user: web:web
    build:
      target: development_build
      context: ..
      dockerfile: ./docker/django/Dockerfile
      cache_from:
        - "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:dev"
        - "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:latest"
        - "*"
    depends_on:
      - database
    logging: *default-logging
    restart: "${DOCKER_RESTART:-no}"
    env_file:
      - ../.env

  rabbitmq:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/rabbitmq:3.7-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - /var/lib/rabbitmq
    logging: *default-logging
    restart: "${DOCKER_RESTART:-no}"
    env_file:
      - ../.env

  redis:
      image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/redis:6.2.5"
