version: "3.7"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"


volumes:
  rabbitmq_data:
    name: credit_robot_ru_rabbitmq
  django-static:
    name: credit_robot_ru_static
  django-media:
    name: credit_robot_ru_media
  prometheus-metrics-server:
    name: credit_robot_ru_prometheus_metrics_server
  prometheus-metrics-worker:
    name: credit_robot_ru_prometheus_metrics_worker


services:
  logstash:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/logstash:7.9.2"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - "ES_SUFFIX=prod"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/ca.crt:/etc/logstash/config/certs/ca.crt:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    logging: *default-logging
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - ../.env

  rabbitmq:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/rabbitmq:3.7-management-alpine"
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging: *default-logging
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - ../.env

  server:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:${RELEASE_VERSION}"
    build:
      target: production_build
      context: ..
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: production
      cache_from:
        - "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:dev"
        - "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:latest"
        - "*"
    command: sh ./docker/django/product-entrypoint.sh
    environment:
      - RABBITMQ_HOST=rabbitmq
      - LOGSTASH_HOST=logstash
    volumes:
      - django-static:/code/static/
      - django-media:/code/media/
      - prometheus-metrics-server:/code/prometheus_metrics
    depends_on:
      - rabbitmq
    logging: *default-logging
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - ../.env

  worker:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:${RELEASE_VERSION}"
    build:
      target: production_build
      context: ..
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: production
      cache_from:
        - "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:dev"
        - "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru:latest"
        - "*"
    command: python manage.py rundramatiq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - LOGSTASH_HOST=logstash
      - dramatiq_prom_host=0.0.0.0
      - dramatiq_prom_port=9191
    volumes:
      - django-static:/app/static/
      - django-media:/code/media/
      - prometheus-metrics-worker:/code/prometheus_metrics
    depends_on:
      - rabbitmq
    logging: *default-logging
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - ../.env

  server-nginx:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/nginx:1.19"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - "8101:80"
      - "9191:9191"
    volumes:
      - ./nginx/nginx.conf_template:/etc/nginx/conf.d/default.template
      - django-static:/static/
      - django-media:/media/
    depends_on:
      - server
    logging: *default-logging
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - ../.env

  rabbitmq-monitoring:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/rabbitmq-exporter:latest"
    restart: "${DOCKER_RESTART:-always}"
    ports:
      - "9519:9419"
    environment:
      - "RABBIT_URL=http://rabbitmq:15672"

  docker-monitoring:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/cadvisor:latest"
    restart: "${DOCKER_RESTART:-always}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /data/docker/:/var/lib/docker:ro
    ports:
      - "8180:8080"

  redis:
    image: "gitlab.rnd.lime-zaim.ru:5000/credit-robot/credit_robot_ru/redis:6.2.5"

